# environment.yml
name: AFIM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - numpy
  - pandas
  - pygmt
  - matplotlib
  - dask
  - xesmf
  - geopandas
  - netCDF4
  - scipy
  - cmocean
  - cartopy
  - seaborn
  - tqdm
  - pyproj        # <-- Add this
  - zarr          # <-- Add this
  - pip
  - pip:
      - myst-parser
      - sphinx
      - sphinx_rtd_theme
      - nbsphinx     # <-- only if you want Jupyter notebook support

