from setuptools import setup, find_packages

setup(
    name="AFIM",
    version="0.1.0",
    description="AFIM: Antarctic Fast Ice and Pack Ice Metrics toolkit for CICE model outputs",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Daniel Patrick Atwater",
    author_email="daniel.atwater@utas.edu.au",
    url="https://github.com/dpath2o/AFIM",
    project_urls={
        "Documentation": "https://AFIM.readthedocs.io/en/main/",
        "Source": "https://github.com/dpath2o/AFIM",
    },
    license="MIT",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    include_package_data=True,
    install_requires=[
        "xarray",
        "numpy",
        "pandas",
        "pygmt",
        "matplotlib",
        "dask",
        "xesmf",
        "geopandas",
        "netCDF4",
        "scipy",
        "cmocean",
        "cartopy",
        "seaborn",
        "tqdm",
        "sphinx",
        "myst-parser",
        "sphinx_rtd_theme",
    ],
    extras_require={
        "docs": [
            "sphinx",
            "sphinx_rtd_theme",
            "nbsphinx",
            "myst-parser",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Programming Language :: Python :: 3",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Atmospheric Science",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
)
