#+TITLE: Australian Fast Ice Modelling
#+subtitle: Grounded Icebergs
#+BIND: org-export-latex-title-command ""
#+LATEX_HEADER: \def\ORGTITLE      {AFIM}
#+LATEX_HEADER: \def\ORGAUTHOR     {DP@H$_2$O}

* Concept
  Examine sequential Sentinel-1/2 images and see which icebergs aren't moving. These could be mapped
  and form the prescribed field of grounded bergs for AFIM.
  I recommend you point your browser to https://coastwatch.noaa.gov/cw_html/cw_polygon_search.html
  Hit the "S-1A/B NRCS" radio button and draw a polygon around Cape D.
  Then choose some fairly recent dates (Within the past 2 years). If you do a 1-month window, you
  should be rewarded with quite a few SAR snapshots of Cape Darnley and its glorious icebergs.
  E.g., see if you can find this guy by entering appropriate search parameters:
  https://www.star.nesdis.noaa.gov//data/socd3/coastwatch/products/nrcs/L2/browse/2020/261/S1A_ESA_2020_09_17_15_45_35_0653672735_068.47E_68.33S_HH_C_nrcs_level2.png
  Sentinel-1 (which is the S-1A/B entered above) is a synthetic aperture radar. Long story short:
  great at discriminating between icebergs and sea ice. Sentinel-1 gives us sufficient resolution to
  see iceberg shape, which gives the potential for us to unequivocally state which bergs are truly
  grounded.
  
* Alex's PoA
** Image Pair
   1. Go to [[https://coastwatch.noaa.gov/cw_html/cw_polygon_search.html][NOAA's Coastwatch Website]]
   2. On that page select ``S-1A/B NRCS'' radio button and draw a polygon around a region. In this
      case (example) I'm using [[Cape Darnley]]
   3. Examine sequential (12-day) Sentinel-1/2 images and see which icebergs aren't moving.
   4. Note the date/time/platform (S1a or b) of the image pair
   5. possible image 1:
	https://www.star.nesdis.noaa.gov//data/socd3/coastwatch/products/nrcs/L2/browse/2022/079/S1A_ESA_2022_03_20_15_21_00_0701104860_072.90E_68.49S_HH_C_nrcs_level2.png
   6. possible image 2:
	https://www.star.nesdis.noaa.gov//data/socd3/coastwatch/products/nrcs/L2/browse/2022/091/S1A_ESA_2022_04_01_15_21_00_0702141660_072.90E_68.49S_HH_C_nrcs_level2.png 
*** Download the image pair
    1. Before downloading the python environment needs to be loaded to recognise the required python
       modules -- assuming [[local buffer configuration]]
    2. Also it very beneficial to understand [[https://sentinelsat.readthedocs.io/en/master/api_overview.html][python module sentinalsat]] , which in my particular case
	I've opted to use [[~/.netrc]] file to store my sensitive login information
    3. One must create a [[https://geojson.org][GeoJSON]] file and edit this code to work on that file
    4. For this particular instance (example) I'm using [[~/PHD/etc/Mawson.geojson]]
       #+BEGIN_SRC python
	 #LIBRARY IMPORT
	 import os
	 import pprint
	 from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
	 # HARDWIRED PARAMETERS -- need a better way of putting a passocde in here
	 Dbase  = os.path.join('/','Users','dpath2o')
	 Ddata  = os.path.join(Dbase,'DATA','Satellite','Sentinel','MawsonCoast')
	 Fgeoj  = os.path.join(Dbase,'PHD','etc','Mawson.geojson')
	 # The geojson file makes this a bit transferable and easier to setup different regions
	 # later on, but it requires that sentinalsat can use and we use to functions from the
	 # sentinelsat API
	 ftprt  = geojson_to_wkt(read_geojson(Fgeoj))
	 # IMAGE 1 -- using a narrow 
	 qkwar  = {'platformname': 'Sentinel-1',
		   'producttype': 'GRD',
		   'date': ('2022-03-20T15:20:00.000Z','2022-03-20T15:25:00.000Z' ),
		   'instrumentshortname': 'SAR-C SAR',
		   'sensoroperationalmode': 'EW'}
	 apic     = SentinelAPI(None, None, 'https://scihub.copernicus.eu/dhus')
	 Qresults = apic.query(ftprt,**qkwar)
	 Qdf      = apic.to_dataframe(Qresults)
	 for f in Qresults:
	     print('Filename {}'.format(Qdf.title[f]))
	     online_test = apic.get_product_odata(f)
	     if not online_test['Online']:
		 print('{} is NOT online ... skipping'.format(Qdf.title[f]))
		 continue
	     apic.download(f,Ddata)
	 # IMAGE 2 -- only changing the datetime to 12 days later as this will give us the exact
	 #            same image
	 qkwar  = {'platformname': 'Sentinel-1',
		   'producttype': 'GRD',
		   'date': ('2022-04-01T15:20:00.000Z','2022-04-01T15:25:00.000Z' ),
		   'instrumentshortname': 'SAR-C SAR',
		   'sensoroperationalmode': 'EW'}
	 apic     = SentinelAPI(None, None, 'https://scihub.copernicus.eu/dhus')
	 Qresults = apic.query(ftprt,**qkwar)
	 Qdf      = apic.to_dataframe(Qresults)
	 for f in Qresults:
	     print('Filename {}'.format(Qdf.title[f]))
	     online_test = apic.get_product_odata(f)
	     if not online_test['Online']:
		 print('{} is NOT online ... skipping'.format(Qdf.title[f]))
		 continue
	 apic.download(f,Ddata)
	 #+END_SRC
	 #+RESULTS:
	 : None
** Rasterise
   #+BEGIN_SRC python
     import rasterio
     from rasterio.warp import calculate_default_transform, reproject, Resampling
     import glob
     import os
     import zipfile
     import tempfile
     Dbase  = os.path.join('/','Users','dpath2o')
     Ddata  = os.path.join(Dbase,'DATA','Satellite','Sentinel','MawsonCoast')
     Dproc  = os.path.join(Ddata,'proc')
     if not os.path.exists(Dproc): os.makedirs(Dproc)
     Fnames = glob.glob("{}/*.zip".format(Ddata))
     CRS    = 'EPSG:3031'
     for f in Fnames:
	 DFin,Fin = os.path.split(f)
	 Fout     = os.path.join(Dproc,'{}.tif'.format(os.path.splitext(Fin)[0]))
	 with tempfile.TemporaryDirectory() as Dtmp:
	     with zipfile.ZipFile(f, 'r') as zip_ref:
		 zip_ref.extractall(Dtmp)  
	     with rasterio.open(os.path.join(Dtmp,"{}.SAFE".format(Fout))) as src:
		 gcps,gcp_crs = src.gcps
		 xfrm,w,h     = calculate_default_transform( gcp_crs , CRS , src.width , src.height ,  gcps=gcps )
		 kwargs       = src.meta.copy()
		 kwargs.update({ 'crs'      : CRS,
				 'transform': xfrm,
				 'width'    : w,
				 'height'   : h,
				 'driver'   : 'GTIFF',
				 'compress' : 'lzw',
				 'NBITS'    : 10 })
		 print(kwargs)
		 with rasterio.open("{}/{}.tif".format(dest_path,dst_name), 'w', **kwargs) as dst:
		     for i in range(1, src.count + 1):
			 reproject( source        = rasterio.band(src, i),
				    destination   = rasterio.band(dst, i),
				    src_transform = src.transform,
				    src_crs       = src.crs,
				    dst_transform = xfrm,
				    dst_crs       = CRS,
				    resampling    = Resampling.nearest)
   #+END_SRC
   #+RESULTS:
** Notes:
   + For Step 1, I reckon we just choose a pair (temporal pair, sorry!) using the NOAA
     coastview. Then note the date/time/platform (S1a or b) and download the appropriate files from
     the sentinel hub. I think I gave you python code to do this earlier - let me know if not.
   + Basically, we should be able to find one high-res swath, then 12 days later we should be able
     to find the corresponding swath from exactly one orbit later (thus finding a pair).  One pair
     should be enough if it's chosen well (i.e., with no surrounding fast ice).  (but we'll need a
     second, low-res "pair" (again separated by 12 days) to cover the northern part of the study area).
   + I have a workflow for SNAP -> geotiffs but first we should find a good pair (couple of pairs -
     one high res, one low res). 
(These could be mapped and form the prescribed field of grounded bergs for [[AFIM]])
# Local Variables:
# org-babel-python-command: "/Users/dpath2o/opt/anaconda3/envs/icepack/bin/python"
# End:
