
#+title: Australian Fast Ice Model
#+subtitle: Administrative
#+date: <2022-04-02 Sat>
#+author: DP@H$_2$O
#+email: daniel.atwater@utas.edu.au
#+STARTUP: indent , overview

* Student Number                                              :admin:numbers:
175611
* Student Universal Identifier (USI)                          :admin:numbers:
DJVW9ZANU3
* Supervisors/Advisors/GRC                                         :contacts:
*** Primary
[[mailto:alexandar.fraser@utas.edu.au][Alex Fraser]]
*** Secondary
[[mailto:will.hobbs@utas.edu.au][Will Hobbs]]
[[mailto:paul.spence@utas.edu.au][Paul Spence]]
*** Graduate Research Coordinator
[[mailto:maximum.nikurashin@utas.edu.au][Max Nikurashin]]
* [[https://www.utas.edu.au/research-admin/graduate-research/current-candidates/support-services][Student Systems and Support Servies]]                              :bookmark:
*** [[https://researchstudent.utas.edu.au/login.aspx?ReturnUrl=%2f][iGrad]]                                             :bookmark:admin:utas:
iGRad is the electronic Candidature Management system.
This system gives you, your supervisors and Graduate Research Coordinator (GRC) an overview of your
candidature, monitors your progress and is where you will submit your Research Plans, Annual Review
Progress Reports and Thesis for Examination.
*** [[https://estudent.utas.edu.au/T1SMProduction/WebApps/eStudent/login.aspx?ReturnUrl=%2fT1SMProduction%2fWebApps%2feStudent%2fdefault.aspx][eStudent Login]]                                    :bookmark:admin:utas:
Access the eStudent self-service portal to manage your personal details, enrol in your coursework
units and monitor your current enrolment and academic progress. Fees information is also accessed
via eStudent. 
For Domestic candidates, the eStudent portal is where you will complete your electronic Commonwealth
Assistance Form (eCAF) and pay your Student Services and Amenities Fees (SSAF). 
*** [[https://www.utas.edu.au/mylo][My Learning Online (MyLO)]]                         :bookmark:admin:utas:
MyLO is the online learning environment at UTAS. MyLO stands for My Learning Online.
Units that you can access via MyLO include any Induction modules you are required to complete and
the compulsory units of the Graduate Certificate in Research (X5A): 
- XGR501: Introduction to Higher Degree by Research
- XGR502: Communicating Research
*** [[https://www.utas.edu.au/students/admin/ssaf][Student Services and Amenities Fee (SSAF)]]               :bookmark:utas:
* Graduate Research Office                                    :contact:admin:
[[mailto:GraduateResearch.CoSE@utas.edu.au][Graduate Research Office for College of Science and Engineering]]
telephone :: +61(0)362268559
Sandy Bay Campus
Centenary Building
Level 3, Room 303
SANDY BAY TAS 7005
[[/Users/dpath2o/Documents/orgs/figs/Sandy-Bay-Campus-Guide.pdf][Sandy Bay Campus Map]]
* Institute of Marine and Antarctic Studies (IMAS)
*** Key Personnel
**** Director of IMAS
- Terry Bailey
**** Head of Oceans and Cryosphere
- Neil Holbrook
*** Commencement
**** IMAS Induction Guide [[https://drive.google.com/file/d/1oDS4qBfGMTNy7of3XoXOIR770i-lU0jt/view?usp=sharing][Online PDF]] :bookmark:
**** IMAS New Student Checklist [[https://drive.google.com/file/d/1WUM0ZtpzSG2RPsk_n7yCUUA2wrmxeFAY/view?usp=sharing][Online PDF]] :bookmark:
* Degree                                                           :noexport:
*** Doctorate of Philosophy (Natural and Physical Sciences)   :bookmark:utas:
[[https://www.utas.edu.au/courses/dvc-research/courses/s9s-doctor-of-philosophy-natural-and-physical-sciences][UTas link to degree]]
*** PhD Commencement Date
<2021-03-05 Fri>
%%(org-date 2021 05 03) PhD Commencement Anniversary %d
*** Anticipated Completion Date
<2026-11-03 Tue>
* Funding                                                             :admin:
*** ADF                                                           :adf:admin:
**** CSS (Civil Schooling Scheme)
***** Apply to CSS
***** DONE Send CSS Draft Application to [[mailto:karen.thomson@defence.gov.au][Karen Thomson]]
CLOSED: [2021-05-12 Wed 09:03]
:PROPERTIES:
:DEADLINE: <2021-05-15 Sat>
:END:
- CLOSING NOTE [2021-05-12 Wed 09:03] \\
  email sent [2021-05-11 Tue]
**** CDF Fellowship
*** Scholarships
**** RTP
see here for details [[https://drive.google.com/file/d/1hFuX_UWDZJjOI3CbTUE5Vub5vQnrqbr7/view?usp=sharing]]
**** AAPP Top-Up
- [[https://universitytasmania.sharepoint.com/:w:/r/sites/AustralianAntarcticProgramPartnership/_layouts/15/Doc.aspx?sourcedoc=%7BD4678FC5-A847-4219-AC35-A9D8E68D830A%7D&file=AAPP%20top-up%20scholarship_FINAL_20200501.docx&action=default&mobileredirect=true][link to document on AAPP Scholarship]]
***** Decision by AAPP panel on [2021-06-24 Thu]
+ application has been withdrawn due to my full time employment
+ should my employment status change I am encouraged to re-submit my application
+ see email from Wen
***** DONE AAPP Scholarship Online Application
CLOSED: [2021-05-10 Mon 13:32] SCHEDULED: <2021-05-07 Fri>
- CLOSING NOTE [2021-05-10 Mon 13:32] \\
  applied on-line after sending Alex the drafting wording and receiving his thumbs-up
[[https://forms.office.com/Pages/ResponsePage.aspx?id=VV3rFZEZvEaNp6slI03uCDs11aTj99RDrN_ronIHAR1UQlJBTFhPNFBBTUtQSVRGVzA3UzI0RFM2My4u][link to application]]
***** Form Contents
IOT draft the content of the online form I've pulled out the fields and
translated them to org headers
***** Candidate Name
Daniel Patrick Atwater
***** Project Title
East Antarctic Fast Ice Model
***** AAPP Project
- [X] Sea Ice
***** Supervisors
- Alex Fraser
- Paul Sandery
- Phil Reid
- Will Hobbs
- Wilma Huneke
***** Current Scholarship
- RTP
***** Date Commenced
<2021-05-03 Mon>
***** Anticipated Completion Date
<2025-11-03 Mon>
***** State how your project is related to the AAPP objectives (max 150 words)
One of three key questions of Theme 3 - Project 6 is addressed by this
research. Specifically the aim of this project is to model fast ice in the East
Antarctic which will elucidate the primary mechanism for the observed variation
and changes of the continental shelf sea-ice mass while laying the ground work
for building a long-range forecasting model. The focus of this project will be
to re-design an existing ice-ocean model to include realistic Antarctic fast
ice. Then using this new East Antarctic Fast Ice Model, I will perform a series
of synthetic experiments to determine the drivers of this fast ice and the role
of dense water formation along the continental shelf. This should elucidate the
recent shift in sea-ice mass extent and allow for future models to better
incorporate sea-ice into Earth system models with a higher degree of confidence.
***** Describe your current progress, including demonstration of any outputs including publications, presentations, etc. (max 250 words)
My current progress is limited to successful enrolment as a remote part-time PhD
candidate with UTas - IMAS - AAPP. I am presently working full-time as a
Meteorological & Oceanographic Officer with the Royal Australian Navy and I am
applying through my employer, in June, for formal recognition of a 20% release rate (i.e. one-day-per-week) to pursue my PhD. At present I
have an informal agreement with my unit of one-day-per-week (and at other times
as work requirements allow); hence they are supportive of this academic
pursuit. However, a formal agreement would carry more weight should I need to be
moved elsewhere in the Navy (i.e. under a different command). It has been
indicated to me that in the merit process of assessing the formal agreement any
additional awards, grants and scholarships that I have been successful in
receiving will help to increase my merit application score with the Navy. In
this same vein I will be applying to the Chief of Defence Force Fellowship. This
is an annual Fellowship that releases ADF members from full-time service to
pursue post-graduate degrees, while still remunerating the member at their
present rate. That application also gives significant weight to additional
grants and scholarships that an applicant presents. Given the strategic
importance of Antartica to our nation and the relevance of understanding AABW
formation as a key driver of the Earth climate system there is a direct
strategic security linkage to this project.
***** I certify that I am not receiving any other form of top-up scholarship
- [X] affirmative
**** Fulbright
used as a travel scholarship to travel and live at an international university for a period of time
*** Fellowships
**** SCAR
* Travel                                                              :admin:
*** DONE [#A] Call Wen about July Travel Bookings
CLOSED: [2021-05-21 Fri 14:03]
- CLOSING NOTE [2021-05-21 Fri 14:03] \\
  decided to defer travel
<2021-05-17 Mon 10:00>
*** Reoccurring
**** BLUF
Total nominal cost $2500
**** Justification
There is an on-going (twice yearly) need for me to travel from my place of
residence in Bomaderry, NSW to UTas-IMAS offices in Hobart, TAS. This will be to
meet with supervisors and attend courses as required. As such it is envisioned
that travel periods will be no longer than one to two weeks. With this in
mind it is my intention here to provide the generalised costings for such travel
using the least expensive method.
***** Considerations
- face-to-face meeting with supervisor(s) which promotes/allows for a more lasting
  human bond to be established/formed/fostered
- physical presence allows for spontaneous networking with other post-graduate
  students and researchers not otherwise achieved
***** Example of Tasks
- intensive residential short-course(s)
- attendance at meetings/conferences/symposiums
- prepare/practice/present a talk/brief
- confirmation of candidature
**** Ground Transport
***** Home to SYD (RTN)
$50
***** HOB to IMAS (RTN)
$40
**** Airfares
***** SYD to HOB (RTN) discount fare
$500
**** Accommodation
***** [[https://www.salamancaterraces.com.au][Salamanca Terraces]]
$1700 weekly rate
***** rationale
- preferred
- my own meal prep/cook
***** weekly food cost grocer
$200
***** Travelodge Hobart
$1300 weekly rate
***** rationale
- save $400 on accommodation, but weekly foot cost of eating out is twice this
***** weekly food cost eating out
$791 (as per ATO daily allowance rate of $113)
*** July 2021
**** Justification
There is a need to meet face-to-face with my supervisors within the first
90-days (FTE) after commencing candidancy. This week (see below) has been identified as a week
in which all supervisors have availablity. The plan will be to drive to Tasmania
as it will be less expensive than to fly. This is with the view that I will be
travelling with my family, wife and two children. The reason for travelling with
family is that they would like to see potentially where we would be living when
I switch to a full-time PhD student. There is a psychological rationale behind
incorporating my family and especially my kids in the trip is that it gives them
a sense of ownership or rather that the entire family is invested in this
academic pursuit that I am embarking upon. This will pay dividends when I am in
the thick of research and looking for their understanding as to why I am doing
this project.
***** Dates
[2021-07-03 Sat]-[2021-07-11 Sun]
***** Kennels
[[https://www.valleykennels.com.au/new_index.htm][Valley Kennels]]
- cost is to come from personal budget
- approximate cost $450
****** CANCELLED contact Valley Kennels to enquire on availability :phone:CANCELLED:
CLOSED: [2021-05-21 Fri 14:04]
- State "CANCELLED"  from "TODO"       [2021-05-21 Fri 14:04]
***** Driving
- Approximate driving time Home to Melbourne 8.5 hr
****** Spirit of Tasmania
- Departs at 1930
- Approximate cost $1500 with cabin each way
- Approximate cost $1100 without cabin
***** Flying
****** Qantas
- Approximate cost $2000; Red E-Deals
***** Accommodation
****** Hotels
$1500 based on Salamanca Terraces rate for six nights
****** Air BnB / Short-term Rental
$1200 - $1800 based on search conducted
****** House-sitting
******* DONE Post to FB IMAS Postgrads
CLOSED: [2021-04-28 Wed 20:52]
- CLOSING NOTE [2021-05-02 Sun 20:52]
* Affiliations and Linkages                                    :colab:
** Antarctic and Sea Ice Experts
+ Robert Massom
+ Petra Heil
** Modelling Experts
+ Phil Reid
+ Paul Sandery
+ Andrew Kiss
** Institute of Low Temperature Science Hokkaido University
[[http://www.lowtem.hokudai.ac.jp/en/index.html]]
*** Kay Ohshima                                    :moorings:CTD:data:source:
[[http://www.lowtem.hokudai.ac.jp/wwwod/~ohshima/index_e.html]]
** Australian Antarctic Program Project (AAPP)                     :bookmark:
#+NAME: AAPP
[[http://aappartnership.org.au][Australian Antarctic Program Project]]
*** [[AAPP]] [[https://aappartnership.org.au/theme-3/][Theme 3]]
**** Leaders
- Petra Heil
- [[https://www.utas.edu.au/profiles/staff/imas/philip-boyd][Phillip Boyd]]
**** Project 6: Sea Ice
***** Leaders
- [[https://aappartnership.org.au/our-researchers/#hobbs][Will Hobbs]]
- [[https://www.antarctica.gov.au/science/meet-our-scientists/dr-klaus-meiners/][Klaus Meiners]]
**** Associated PhD Projects
***** Zhaohui Wang
analysisng effect of including realistic sea ice in a NWP
*** Personnel
**** AAPP Director
***** [[mailto:n.bindoff@utas.edu.au][Nathan Bindoff]]
**** Specific Administration Manager
***** [[mailto:wenneke.tenhout@utas.edu.au][Wenneke Ten Hout]]
**** General Administration
***** Clair Rutherford
** Consortium on Ocean-Sea Ice Modelling in Australia (COSIMA) :bookmark:
#+NAME: COSIMA
[[http://cosima.org.au][COSIMA]]
*** ARC plan proposal                                           :ref:pivotal:
[[./references/modelling/COSIMA_Hogg_ARC_submitted_220420_project_description.pdf][ARC plan proposal]]
