#!/bin/bash
#PBS -P gv90
#PBS -q normalbw
#PBS -N plot_daily_maps
#PBS -l walltime=24:00:00
#PBS -l mem=48GB
#PBS -l ncpus=12
#PBS -l storage=gdata/gv90+gdata/hh5+gdata/jk72
#PBS -o plot_daily_maps.out
#PBS -e plot_daily_maps.err

module use /g/data/hh5/public/modules
module load conda/analysis3-24.07

cd ~/AFIM/src/AFIM/scripts/
python plot_daily_maps.py --sim_name gi-min-elps-def --ice_type SO --var_names ispd aice hi divu
