#!/bin/bash
#PBS -P gv90
#PBS -q normalbw
#PBS -l walltime=5:00:00
#PBS -l mem=74GB
#PBS -l ncpus=28
#PBS -l jobfs=10GB
#PBS -l storage=gdata/gv90+gdata/xp65
#PBS -j oe
#PBS -v year,sim
module use /g/data/xp65/public/modules
module load conda/analysis3-25.05
echo "Starting OSI-SAF regridding with AFIM sim ${sim} for year ${year} on host: $(hostname)"
cd ~/AFIM/src/AFIM/scripts/regridding
python3 reG_OSISAF_ispd.py --year ${year} --sim ${sim}